/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/screens/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#511b00",
        "surface-variant": "#e5e2e1",
        "surface-bright": "#ffffff",
        "secondary-container": "#ffb596",
        "on-primary-fixed": "#360f00",
        "on-error": "#ffffff",
        "outline": "#8b7267",
        "on-primary-fixed-variant": "#7c2d00",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdbcd",
        "on-surface": "#1c1b1b",
        "outline-variant": "#dec0b4",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed": "#bde9ff",
        "secondary-fixed": "#ffdbcd",
        "secondary-fixed-dim": "#ffb596",
        "inverse-primary": "#ffb596",
        "inverse-on-surface": "#f3f0ef",
        "surface-dim": "#dcd9d9",
        "surface-container-high": "#f0edec",
        "surface-container": "#f6f3f2",
        "inverse-surface": "#313030",
        "surface-container-low": "#fcf9f8",
        "secondary": "#885036",
        "surface-tint": "#a33e00",
        "primary-container": "#ea7034",
        "on-tertiary-fixed": "#001f2a",
        "on-background": "#1c1b1b",
        "tertiary-container": "#00a0cb",
        "tertiary": "#006783",
        "primary": "#a33e00",
        "surface": "#ffffff",
        "on-tertiary-fixed-variant": "#004d64",
        "tertiary-fixed-dim": "#64d3ff",
        "on-secondary-fixed-variant": "#6c3921",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-container": "#7a442c",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb596",
        "on-tertiary-container": "#003140",
        "on-error-container": "#93000a",
        "on-surface-variant": "#574239",
        "on-secondary-fixed": "#360f00",
        "background": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
};
